version: '3.5'
services:
  zookeeper:
    image: clickhouse/clickhouse-keeper:23.3.4.17-alpine
    container_name: zookeeper
    hostname: zookeeper
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10
    ports:
      - "9181:9181"
    volumes:
      - ${PWD}/clickhouse-keeper:/etc/clickhouse-keeper
      - type: volume
        source: keeper
        target: /var/lib/clickhouse
  clickhouse01:
    image: clickhouse/clickhouse-server:23.3.4.17-alpine
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ${PWD}/clickhouse01:/etc/clickhouse-server
      - type: volume
        source: ch01
        target: /var/lib/clickhouse
    depends_on:
      - zookeeper
  clickhouse02:
    image: clickhouse/clickhouse-server:23.3.4.17-alpine
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    volumes:
      - ${PWD}/clickhouse02:/etc/clickhouse-server
      - type: volume
        source: ch02
        target: /var/lib/clickhouse
    depends_on:
      - zookeeper
  clickhouse03:
    image: clickhouse/clickhouse-server:23.3.4.17-alpine
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    volumes:
      - ${PWD}/clickhouse03:/etc/clickhouse-server
      - type: volume
        source: ch03
        target: /var/lib/clickhouse
    depends_on:
      - zookeeper
  clickhouse04:
    image: clickhouse/clickhouse-server:23.3.4.17-alpine
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.14
    volumes:
      - ${PWD}/clickhouse04:/etc/clickhouse-server
      - type: volume
        source: ch04
        target: /var/lib/clickhouse
    depends_on:
      - zookeeper

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24

volumes:
  keeper:
  ch01:
  ch02:
  ch03:
  ch04:
